---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: file-sharing-uploads-pv
  labels:
    app.kubernetes.io/name: file-sharing
    app.kubernetes.io/component: storage
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: manual
  hostPath:
    path: /tmp/file-sharing-uploads
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: file-sharing-uploads-pvc
  namespace: file-sharing
  labels:
    app.kubernetes.io/name: file-sharing
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: file-sharing-logs-pv
  labels:
    app.kubernetes.io/name: file-sharing
    app.kubernetes.io/component: logs
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: manual
  hostPath:
    path: /tmp/file-sharing-logs
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: file-sharing-logs-pvc
  namespace: file-sharing
  labels:
    app.kubernetes.io/name: file-sharing
    app.kubernetes.io/component: logs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: manual
