{{- if .Values.backend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "file-sharing-app.fullname" . }}-backend
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "file-sharing-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      {{- include "file-sharing-app.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        {{- include "file-sharing-app.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: backend
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        runAsNonRoot: {{ .Values.backend.securityContext.runAsNonRoot }}
        runAsUser: {{ .Values.backend.securityContext.runAsUser }}
        runAsGroup: {{ .Values.backend.securityContext.runAsGroup }}
        fsGroup: {{ .Values.backend.securityContext.fsGroup }}
      containers:
        - name: backend
          image: {{ include "file-sharing-app.image" (dict "Values" .Values "repository" .Values.backend.image.repository "tag" .Values.backend.image.tag) }}
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.backend.service.targetPort }}
              protocol: TCP
          env:
            {{- range $key, $value := .Values.backend.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
          securityContext:
            runAsNonRoot: {{ .Values.backend.securityContext.runAsNonRoot }}
            runAsUser: {{ .Values.backend.securityContext.runAsUser }}
            runAsGroup: {{ .Values.backend.securityContext.runAsGroup }}
            allowPrivilegeEscalation: {{ .Values.backend.securityContext.allowPrivilegeEscalation }}
            readOnlyRootFilesystem: {{ .Values.backend.securityContext.readOnlyRootFilesystem }}
            capabilities:
              {{- toYaml .Values.backend.securityContext.capabilities | nindent 14 }}
          volumeMounts:
            - name: uploads
              mountPath: /app/uploads
      volumes:
        - name: uploads
          {{- if .Values.storage.persistentVolume.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "file-sharing-app.fullname" . }}-uploads-pvc
          {{- else }}
          emptyDir: {}
          {{- end }}
---
{{- if .Values.backend.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "file-sharing-app.fullname" . }}-backend-hpa
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "file-sharing-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "file-sharing-app.fullname" . }}-backend
  minReplicas: {{ .Values.backend.hpa.minReplicas }}
  maxReplicas: {{ .Values.backend.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.backend.hpa.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.backend.hpa.targetMemoryUtilizationPercentage }}
---
{{- end }}
{{- if .Values.backend.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "file-sharing-app.fullname" . }}-backend-pdb
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "file-sharing-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  minAvailable: {{ .Values.backend.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "file-sharing-app.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
---
{{- end }}
{{- end }}
