{{- if .Values.frontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "file-sharing-app.fullname" . }}-frontend
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "file-sharing-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "file-sharing-app.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        {{- include "file-sharing-app.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        runAsNonRoot: {{ .Values.frontend.securityContext.runAsNonRoot }}
        runAsUser: {{ .Values.frontend.securityContext.runAsUser }}
        runAsGroup: {{ .Values.frontend.securityContext.runAsGroup }}
        fsGroup: {{ .Values.frontend.securityContext.fsGroup }}
      containers:
        - name: frontend
          image: {{ include "file-sharing-app.image" (dict "Values" .Values "repository" .Values.frontend.image.repository "tag" .Values.frontend.image.tag) }}
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.service.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          securityContext:
            runAsNonRoot: {{ .Values.frontend.securityContext.runAsNonRoot }}
            runAsUser: {{ .Values.frontend.securityContext.runAsUser }}
            runAsGroup: {{ .Values.frontend.securityContext.runAsGroup }}
            allowPrivilegeEscalation: {{ .Values.frontend.securityContext.allowPrivilegeEscalation }}
            readOnlyRootFilesystem: {{ .Values.frontend.securityContext.readOnlyRootFilesystem }}
            capabilities:
              {{- toYaml .Values.frontend.securityContext.capabilities | nindent 14 }}
---
{{- if .Values.frontend.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "file-sharing-app.fullname" . }}-frontend-hpa
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "file-sharing-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "file-sharing-app.fullname" . }}-frontend
  minReplicas: {{ .Values.frontend.hpa.minReplicas }}
  maxReplicas: {{ .Values.frontend.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.frontend.hpa.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.frontend.hpa.targetMemoryUtilizationPercentage }}
---
{{- end }}
{{- if .Values.frontend.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "file-sharing-app.fullname" . }}-frontend-pdb
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "file-sharing-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  minAvailable: {{ .Values.frontend.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "file-sharing-app.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
---
{{- end }}
{{- end }}
