{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name }}
  labels:
    {{- include "file-sharing-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: namespace
{{- end }}
