{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "file-sharing-app.fullname" . }}-frontend
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "file-sharing-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "file-sharing-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
---
{{- end }}
{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "file-sharing-app.fullname" . }}-backend
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "file-sharing-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "file-sharing-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
---
{{- end }}
{{- if .Values.proxy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "file-sharing-app.fullname" . }}-proxy
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "file-sharing-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: proxy
spec:
  type: {{ .Values.proxy.service.type }}
  ports:
    - port: {{ .Values.proxy.service.port }}
      targetPort: {{ .Values.proxy.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "file-sharing-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: proxy
---
{{- end }}
