---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: file-sharing-backend
  namespace: file-sharing
  labels:
    app.kubernetes.io/name: file-sharing
    app.kubernetes.io/component: backend
  annotations:
    description: "Service Account para o backend da aplicação"
automountServiceAccountToken: false

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: file-sharing-frontend
  namespace: file-sharing
  labels:
    app.kubernetes.io/name: file-sharing
    app.kubernetes.io/component: frontend
  annotations:
    description: "Service Account para o frontend da aplicação"
automountServiceAccountToken: false

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: file-sharing
  name: file-sharing-backend-role
  labels:
    app.kubernetes.io/name: file-sharing
    app.kubernetes.io/component: backend
rules:
# Permissões mínimas necessárias para o backend
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["file-sharing-tls", "ca-secret"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["backend-config"]
  verbs: ["get"]
# Permissão para health checks
- apiGroups: [""]
  resources: ["pods"]
  resourceNames: ["file-sharing-backend"]
  verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: file-sharing-backend-binding
  namespace: file-sharing
  labels:
    app.kubernetes.io/name: file-sharing
    app.kubernetes.io/component: backend
subjects:
- kind: ServiceAccount
  name: file-sharing-backend
  namespace: file-sharing
roleRef:
  kind: Role
  name: file-sharing-backend-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: file-sharing
  name: file-sharing-frontend-role
  labels:
    app.kubernetes.io/name: file-sharing
    app.kubernetes.io/component: frontend
rules:
# Permissões mínimas para o frontend
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["file-sharing-tls"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["frontend-config"]
  verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: file-sharing-frontend-binding
  namespace: file-sharing
  labels:
    app.kubernetes.io/name: file-sharing
    app.kubernetes.io/component: frontend
subjects:
- kind: ServiceAccount
  name: file-sharing-frontend
  namespace: file-sharing
roleRef:
  kind: Role
  name: file-sharing-frontend-role
  apiGroup: rbac.authorization.k8s.io
