# Template para configurar repositório privado no ArgoCD
# 1. Primeiro, crie um Personal Access Token no GitHub com permissões de 'repo'
# 2. Aplique este secret substituindo <YOUR_GITHUB_TOKEN>

apiVersion: v1
kind: Secret
metadata:
  name: private-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/rafaelpdemelo/cloudwalk-desafio.git
  password: <YOUR_GITHUB_TOKEN>
  username: rafaelpdemelo

---
# Depois aplique este comando:
# kubectl apply -f argocd/repo-secret-template.yaml
# 
# Em seguida, recrie a aplicação ArgoCD:
# kubectl apply -f argocd/application.yaml
