apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-sharing-frontend
  namespace: file-sharing
  labels:
    app: file-sharing-frontend
    app.kubernetes.io/name: file-sharing
    app.kubernetes.io/component: frontend
    app.kubernetes.io/version: "1.0.0"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: file-sharing-frontend
  template:
    metadata:
      labels:
        app: file-sharing-frontend
        app.kubernetes.io/name: file-sharing
        app.kubernetes.io/component: frontend
      annotations:
        checksum/config: "placeholder"
    spec:
      serviceAccountName: file-sharing-frontend
      automountServiceAccountToken: false
      
      # Security Context no nível do Pod
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
        fsGroupChangePolicy: "OnRootMismatch"
        seccompProfile:
          type: RuntimeDefault
        supplementalGroups: [1001]
      
      containers:
      - name: frontend
        image: rafaelpdemelo/desafiofilesharing:frontend-security-v2
        imagePullPolicy: Always  # Pull do DockerHub
        
        # Security Context no nível do Container
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1001
          runAsGroup: 1001
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
        
        ports:
        - name: http
          containerPort: 3001
          protocol: TCP
        
        env:
        - name: BACKEND_URL
          value: "https://file-sharing-backend:3000"
        - name: NODE_ENV
          value: "production"
        
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        
        # Probes de saúde
        livenessProbe:
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        
        readinessProbe:
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
          successThreshold: 1
        
        startupProbe:
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 30
          successThreshold: 1
        
        volumeMounts:
        - name: nginx-cache
          mountPath: /var/cache/nginx
        - name: nginx-run
          mountPath: /var/run
        - name: tmp-dir
          mountPath: /tmp
      
      volumes:
      - name: nginx-cache
        emptyDir:
          sizeLimit: 100Mi
      - name: nginx-run
        emptyDir:
          sizeLimit: 100Mi
      - name: tmp-dir
        emptyDir:
          sizeLimit: 100Mi
      
      # Configurações de segurança adicionais
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      
      # Anti-affinity para distribuir pods
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - file-sharing-frontend
              topologyKey: kubernetes.io/hostname
