apiVersion: v1
kind: Namespace
metadata:
  name: file-sharing
  labels:
    name: file-sharing
    app.kubernetes.io/name: file-sharing
    app.kubernetes.io/instance: file-sharing
    # Pod Security Standards - Enforcing restricted policy
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
  annotations:
    description: "Namespace para aplicação segura de compartilhamento de arquivos"
